### ISSUE TITLE
GHRSST dataset for SST assimilation

### ISSUE THREAD

**Issue by haze1986** [sakov/enkf-c#19]
Hi Devs,

I am trying to add in the SST dataset (GHRSST) for assimilation from CMEMS database, example:
https://www.ncei.noaa.gov/data/oceans/ghrsst/L3C/GLOB/AVHRR_SST_METOP_B_GLB/OSISAF/2022/013/

I have specified in obs.prm as below:

product == GHRSST
type = SST
reader = gridded_xy
parameter VARNAME = sea_surface_temperature
parameter VARSHIFT = -273.15
file = obs/20180102120000*.nc

The program seems to be able to read it, but I am getting the following outputs

 PRODUCT = GHRSST, TYPE = SST, reader = gridded_xy
      reading obs/20180102120000-OSISAF-L3C_GHRSST-SSTsubskin-AVHRR_SST_METOP_B_GLB-sstglb_metop01_20180102_120000-v02.0-fv01.0.nc:
        VARNAME = sea_surface_temperature
        LONNAME = lon
        LATNAME = lat
        (ni, nj) = (7200, 3600)
        nobs = 8153894
        # obs added = 40276
      id = 2504 - 42779
      total 40276 observations
      40161 valid observations
      min day = 0.000
      max day = 0.000
        bad observation detected: type = SST, product = GHRSST, instrument = METOP_B, datafile = obs/20180102120000-OSISAF-L3C_GHRSST-SSTsubskin-AVHRR_SST_METOP_B_GLB-sstglb_metop01_20180102_120000-v02.0-fv01.0.nc, id = 2504, original id = 2504, batch = 0, value = 23.2, estd = nan, footprint = 0, lon = 96.725, lat = -2.325, depth = 0.0, model_depth = 4730.2, fi0 = 85.165, fi1 = 0.522, fi2 = 0.000, fk = 0.000, time = 0, status = 0

  ERROR: enkf: CPU #0: bad observation

Have I specified the prm correctly?

**Comment by sakov** [comment]
Hi haze1986,

1. PREP exited with error because of "estd = nan". To proceed with reading in this data you need to specify observation error. There are two ways of doing it: 

(a) by specifying a variable in data file e.g.

product == GHRSST
type = SST
reader = gridded_xy
parameter VARNAME = sea_surface_temperature
parameter VARSHIFT = -273.15
parameter ESTDNAME = sses_standard_deviation
parameter TIMENAMES = time sst_dtime
file = *.nc

(b) by specifying it explicitly

product == GHRSST
type = SST
reader = gridded_xy
parameter VARNAME = sea_surface_temperature
parameter VARSHIFT = -273.15
parameter TIMENAMES = time sst_dtime
error_std = 0.3
file = *.nc

(c) or by a combination of the above, e.g.

parameter ESTDNAME = sses_standard_deviation
error_std = 0.3 PL

One can get some leads by running "enkf_prep --describe-prm-format obsdata", "enkf_prep --describe-reader gridded_xy", and from the user manual.

2. Having said that, we always pre-process L2P data to reduce the number of obs. and standardise further treatment. The standard preprocessing for AVHRR, AMSR2 and VIIRS involves collating on virtual 4-km grid in 6-hourly windows (this keeps the time of individual obs.).

3. Because we rarely use reader "gridded_xy" on L2P data, this reader still does not handle parameter "ADDVAR" necessary for adding sses_bias (which exists for reader "scattered"). I will add it tomorrow.

Cheers,
Pavel Sakov
