### ISSUE TITLE
Data details and results evaluation

### ISSUE THREAD

**Issue by shahbazbaig** [sakov/enkf-c#22]
Hi,

I tried to execute all provided examples with provided datasets which ran quite easily. But i noticed that .nc files are just holding metadata which is appearing in Panoply (NC reader) tool but nothing to plot or see in these files. Can you please share the reason of this strange type of files. secondly, How can I see the results as there are number of files are generated by examples script under their respective folders? 

I also tried to go through the Guide book but that is more about theory instead of your code description. Can you please let me know if you have any detailed document about code description.

Thanks.

**Comment by sakov** [comment]
Hi Shahbaz,

I do not quite understand the problems. Perhaps you could ask someone around for help.

>But i noticed that .nc files are just holding metadata which is appearing in Panoply (NC reader) tool but nothing to plot
>or see in these files. Can you please share the reason of this strange type of files.

I guess by results you mean analysis or increment model files. The attributes of variables in these files are copied from the input (forecast, or background) files... Could you elaborate?

>How can I see the results as there are number of files are generated by examples script under their respective folders?

If you mean viewing data in NetCDF files -- try ncview... although this question is misplaced here

>Can you please let me know if you have any detailed document about code description

No, just the code itself. (Interesting request)

Cheers,
Pavel Sakov

**Comment by shahbazbaig** [comment]
Hi Pavel,

Thanks for your kind response. I managed to visualize the example data. I
have one more question regarding results/output. Can you please tell me how
can I get the output like sst-spread.nc file as there are many files in
ensemble_6565 and ensemble_static. Can you please also give me a Hint,
about what are these folders actually representing?

kind regards,

Shahbaz Baig
*Remote Sensing & GIS Specialist*

**Comment by sakov** [comment]
Hi Shahbaz,

> Can you please tell me how can I get the output like sst-spread.nc file

./enkf_update
  Usage: enkf_update <prm file> [<options>]
  Options:
<...>
  --calculate-spread
      calculate forecast and analysis ensemble spread and write to spread.nc
<...>

(And there are a few more options concerning calculating ensemble spread.) So one needs to add this or a similar option to the command line when running enkf_update, and the spread will be written to ./spread.nc. The examples are configured to run with this option, so just look at spread.nc after running e.g. "make enkf".

You may also want to look at observations.nc, inflation.nc, vcorr.nc, and *.out logs, particularly at the innovation stats in the tail of calc.out.

>Can you please also give me a Hint, about what are these folders actually representing?

"ensemble_6565" contains restarts for each member at day 6565 (since 19900101), i.e. the (dynamic) forecast ensemble for the EnKF. After calculating analysis with EnKF (by running PREP, CALC, and UPDATE, or "make enkf") the analysed ensemble, or increments for each member (depending on the options to UPDATE) will be written to the same directory.

"ensemble_static" contains static ensemble for EnOI.

"background_6565" contains the background for the EnOI. After calculating analysis with EnOI ("make EnOI") it will be written to this directory.

I am going to close this issue because IMO it is not an "issue" about the code, but you are welcome to ask questions privately via email. (But do the homework, too -- read the User Guide, try to understand what happens after running make, step through the code when necessary...)

Best regards,
Pavel Sakov
